# Generated by Django 4.1.6 on 2023-04-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
