# Generated by Django 4.2 on 2023-04-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educapedia', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
