# Generated by Django 4.2 on 2023-04-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educapedia', '0006_alter_customuser_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
