# Generated by Django 4.2 on 2023-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educapedia', '0011_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='assignment',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='quiz',
            field=models.URLField(),
        ),
    ]
