# Generated by Django 4.2 on 2023-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educapedia', '0016_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='courses',
            name='picture',
            field=models.ImageField(upload_to='media/static/pictures/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video1',
            field=models.FileField(upload_to='media/static/videos/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video2',
            field=models.FileField(upload_to='media/static/videos/'),
        ),
    ]
